server:
  port: 9994
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///ecommerce
    username: root
    password: Md7$#1998
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:ecommerce.object_jars.dto.NOrderConfirmation,paymentConfirmation:ecommerce.object_jars.dto.PaymentConfirmation
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: mdmangesh70@gmail.com
    password: omjnltcwrbnvttpx
    port: 587


#        connectiontimeout: 5000
#        timeout: 3000
#        writetimeout: 5000
        
         
        
        
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=mdmangesh70@gmail.com
#spring.mail.password=omjnltcwrbnvttpx
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true        